version: "3"
services:
  express-app:
    build:
      context: .
      # args:
      #   - NODE_ENV=production
      target: production
    ports:
      - "3000:5001"
    environment:
      - NODE_ENV=production
    command: npm run start
