version: "3"
services:
  express-app:
    container_name: express-app-container
    ports:
      - "3000:5001"
    env_file:
      - ./.env
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
